### ISSUE TITLE
How to train the boundary branch?

### ISSUE THREAD

**Issue by AI-Zhpp** [GrassBro/WSID-Net#1]
Thanks for your great work. Through the whole paper. I only find the structure of the Boundary branch. As stated in the paper, there are no boundary label. How can you train the boundary branch?

**Comment by GrassBro** [comment]
We follow the assumption that boundaries exist in pixel locations between different classes. Based on this setting, we extract pseudo labels from the class activation map. For more details please refer to our baseline IRN. Please also feel free to raise any questions you still do not understand.
